### ISSUE TITLE
Update the create subscription endpoint to handle subscriptions of generic events.

### ISSUE THREAD

**Issue by OddArneSaetervik** [Altinn/altinn-events#107]
### Description

The create subscription endpoint must be able to separate the authorization requirement of app events and generic events.

### Additional Information

Authorization is out of scope for this change. This will be added by separate issue.

### Tasks

- [x] Add a code path to handle generic events. 
    - [x] Check for app event by analysing the sourceFilter.
    - [x] Ensure that no app specific logic stops the storage of the subscription. E.g validation of subject.
    - [x] Explicit check of scope in code (not attribute). altinn:events.subscribe 
    ~~- [ ] Input validation to prevent things like SQL-injection~~ Handled by repository logic
- [ ] Test
  - [x] Unit tests  
  - [x] Manual test
~~- [ ] Documentation~~ extracted to #266 
- [x] Create automated tests

### Acceptance criteria
- [x] Request with a non app source without scope is denied.
- [x] Valid request returns 201.
- [x] Creating app subscription without scope still works.
- [x] Creating app subscription is unaffected.
- [x] URI different from URL or URN is denied.
- [x] Created issue for adding authorization of generic events to the subscription endpoint. #259
