### ISSUE TITLE
Create a new endpoint for listing of events

### ISSUE THREAD

**Issue by OddArneSaetervik** [Altinn/altinn-events#108]
### Description
It should be possible for external parties to get a list of events based on some search criteria. The endpoint should require a filter for the event source property.
[Open API spec for endpoint available here](https://app.swaggerhub.com/apis/vgrk/altinn-platform_events/v1)

Endpoint:
/events/api/v1/events?source={sourcefilter}

### Additional Information

- Should all query parameters (as described in OAS) be implemented as part of this issue?
  - No, we should limit the initial implementation to: `source`, `after`, `subject`, `type`, and `size`. The reason is to only prioritize what is needed for an MVP.
- Required parameters? (in planning we discussed if it is enough to have source as the only mandatory field, the concern is index utilization and performance).
  - `source` is the only mandatory parameter for event producers
  - `source`, `subject` and `after` are mandatory for subscribers

- Scopes?
  - Only `altinn:events.subscribe` should give access to this endpoint

### Tasks

- [x] Rework stored procedure to retrieve event from events database
- [x] Update service if required
- [x] Implement endpoint
- [x] Implement unit tests
- [x] QA
- [x] Test
  - [x] Manual test
  - [x] Automated test
- [x] Implement k6 tests
- [x] Documentation (see `feature/events` branch in studio-docs repo)
  - [x] Swagger examples? 
  - [x] Update swagger in docs
  - [x] User documentation?
- [x] Update APIM in AT
- [x] Describe remaining work (additional query parameters, etc) in an issue.
- [x] Create Issue specifying remaining work to set up authorization for endpoint exists and is well defined.

  > Additional work related to indexes: #292
  > Add support for filtering by date range: #293 
 
~~Test performance with 10 million events~~
~~Add indexes where necessary~~

### Acceptance Criteria

- [x] GET /events/ with `source` and `after` returns 200 OK with list of events
- [x] GET /events with required parameters and (type or size) returns 200 OK with list of events
- [x] GET /events with missing token = 401
- [x] GET /events with missing scope = 403
- [x] GET /events with missing required parameters = 400

**Comment by b-brodie-digdir** [comment]
@acn-sbuad Should `after` be required here? In `GetForOrg` we require either `from` or `after`.

**Comment by acn-sbuad** [comment]
Let's keep from for now, and extend to after and to at a later point.

**Comment by b-brodie-digdir** [comment]
We discussed this briefly before planning. It seems as though specifying at least one `source` is a requirement we must enforce for performance reasons. Specifically, we want to avoid retrieving events that we know ahead of time will fail authorization checking.

**Comment by b-brodie-digdir** [comment]
`after` has been specified as being required. This seems to be inconsistent with our handling of the parameter as we often send a dummy value (such as "0") when testing in order to get all events from the beginning. Should we consider making it optional instead?

**Comment by acn-sbuad** [comment]
Subject as a header parameter was not specified in the Open API spec, will need to look closer into this. Otherwise tested ok

**Comment by SandGrainOne** [comment]
Should we have a max for the size parameter?

**Comment by acn-sbuad** [comment]
1. If asking for a too large set of events will result in poor performance for other users then we probably should, but I guess that hasen't been the case yet.. What would be a resonable limit? 
2. Isn't this by design? Not a continuation token, but more a pointer as to where they left the stack of events to know which events to process next regardless if they exist at the time the response is returned?

**Comment by SandGrainOne** [comment]
1. I've been thinking a maximum og 1000. We could silently reduce the size down to 1000 if the given value is higher.
2. Yeah I can see the use. "Hold on to the last next link so you have the start point for next "session"." Could be used like that. I was thinking that the next link indicate that we already have more events to download.
