### ISSUE TITLE
Update the push outbound endpoint to handle generic events and app events

### ISSUE THREAD

**Issue by OddArneSaetervik** [Altinn/altinn-events#109]
### Description
The push endpoint currently responsible for identifying subscriptions and placing push messages in the events-outbound queue must be able to handle generic events.

Currently, if an event does not speficy a subject (an optional property for cloud event), we do not attempt to retrieve matching subscriptions. This is one of potentially more issues that need to be fixed to be able to handle push of genering events

### Tasks

- [x] Update GetSubscription function in database to handle all event properties being optional
- [x] Update OutboundService to handle all event properties that are optional
- [x] Introduce alternative authorization flow for generic events in AuthorizeAndEnqueueOutbound
- [x] QA
- [x] Manual test
~~- [ ] Implement k6 tests for new functionality ~~ handled in #166

### Acceptance Criterias
- [x] If an active subscriptions exists and event should be pushed to the endpoint
- [x] If an inactive subscriptions exists and event should be NOT be pushed to the endpoint
- [x] Regression test of push events for app events i successful

**Comment by acn-sbuad** [comment]
Generic events missing properties _subject_ and _time_ are not pushed to subscribers
