### ISSUE TITLE
Rename EventsController to AppEventsController

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#110]
### Description

All endpoints on the current EventsController are specific to events from apps. Even the endpoints path have app in them.

E.g. /events/api/v1/app/party

To make room for more generic events we rename current EventsController to AppEventsController. Content and Authorization should be the same. 

### Tasks

- [x] Rename the EventsController
- [x] Update tests as needed.
- [x] Update documentation as needed.

### Acceptance Criterias

- [x] No functional changes. All endpoints still work.
