### ISSUE TITLE
Create a TimeService that can serve the time.

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#111]
### Description

The events component is in need of a mechanism to synchronize time across multiple instances/pods of the application. 

We need to investigate how accurat kubernetes manage to keep the current time across pods. Can se simply just use DateTime.Now or do we need a more accurate centralized mechanism.

### Additional Information

Time sync for Windows VMs in Azure:
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/time-sync

Time sync for Linux VMs in Azure:
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync

### Tasks

- [ ] Define a new interface for a time service
- [ ] Implement a TimeService with a single endpoint for current time.
- [ ] Make the TimeService available through ServiceProvider.

### Acceptance Criteria

- [ ] A new TimeService is made available for other services through the ServiceProvider.

**Comment by bengtfredh** [comment]
We use linux nodes - link for timesync:
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync

**Comment by SandGrainOne** [comment]
Not critical for the work we do with improvements in Events.

**Comment by SandGrainOne** [comment]
All nodes and machines are syncronized following Microsoft recommendations in Azure.
