### ISSUE TITLE
Change POST App event endpoint to push event to event-registration queue

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#118]
### Description

The existing endpoint for storing (and pushing) incoming app events is changed to put new events on to the events-registration queue, rather than attempting to save them to persistent storage immediately.

The logic should:

- Give the event an ID
- Give the event a time stamp
- Put on queue event-registration

### Tasks

- [x] All incoming events should be given a timestamp
- [x] Create a new method in the EventsService to perform the PUT to queue. `/inbound`
- [x] Use new name for outbound endpoint, `/outbound`, previously `/push`
- [x] Rewrite the logic behind the endpoint to put event on queue.
- [x] Create inserteventV2 function that takes time as a parameter, instead of setting it in SQL
- [x] Review/QA
- [x] Documentation (docs) The events illustration must be updated to show the new queue.
- https://github.com/Altinn/altinn-studio-docs/pull/722

### Acceptance Criteria

- [x] Events show up on the events-registration queue with a timestamp set by the new endpoint.
