### ISSUE TITLE
Change table-name events

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-events#120]
### Description

Table events in postgres should be renamed since we will use this table-name for general events.

Write a procedure for how we go about doing this rename with as little downtime as possible.

While migrating the reads from the registration queue must be paused.

### Consideration
Should older migration scripts be changed to use the new name? 

### Procedure
-  Create PR to adjust table and function/procedure name in migration scripts and repository class
- Disable automatic deploy for events component
- Merge PR

**In each environment**
- Stop registration function
- Wait until all other queues, inbound, outbound are empty
- Deploy release containing code that goes towards the new table name 
- Once all pods are up and running, start registration function
- Monitor environment for failures. 

### Tasks

- [x] Plan and describe the procedure for how to execute this operation in this issue.
- [x] Rename table events to events_app
- [x] Modify all procedures and functions to use new table
- [x] QA
- [x] Execute change in AT-environments
- [x] Execute change in YT-environment
- [x] Execute change in TT-environment
~~- [ ] Execute change in Prod-environment (Release-329)~~ extracted into #200

### Acceptance Criterias
- [x] Events are successfully registered and persisted in database
- [x] Events are successfully pushed to subscribers
- [x] GET events endpoint returns expected response for org and party
