### ISSUE TITLE
Create an OpenAPI specification for the new version of Events with the new endpoints.

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#125]
### Description

There is a need to have an OpenAPI specification ready for use in meetings with external parties. This specification can also be used as basis for development of the endpoints.

### Tasks

Events
- [x] Define endpoint for POST of new event
- [x] Define endpoint for GET by ID.
- [x] Define endpoint for GET Events. List of CloudEvents. Possible search parameters?

Subscription
 - [x] Reuse existing endpoints

It should not be possible to update or delete events.

### Acceptance Criterias

- [ ] Finished OpenAPI specification.
