### ISSUE TITLE
Subscription duplicate check

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#129]
### Description

The current logic will allow the same consumer to create multiple identical subscriptions. The Subscription logic should be able to stop this from happening.

Same subscription is identified when all properties are the same as an existing subscription. Excluding ID and alternative subject.

If a duplicate is found:
- The endpoint returns 201 with the original subscription.
- Trigger subscription validation. (if not already valid)

### Tasks

- [x] Create a new function that can look for existing subscription based on properties from a new one
- [x] Change logic in service to first look for existing subscription. Return existing if found instead of saving new.
- [x] Expand function return columns to include validation.

### Acceptance Criterias

- [x] The POST endpoint for subscription returns the ID of an existing subscription if it matches the new properties
- [x] The re-registration of a subsription triggers validation if the previous validation status was invalid.
- [x] The returned subscription includes validation status (true/false)
