### ISSUE TITLE
Create a new PostgreSQL 14 Server for the Events database

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#141]
### Description

Perform the necessary terraform changes to create a new PostgreSQL server for Events.

### Tasks

- [x] Create Terraform tag 1.4.3 containing code for removing the "old" postgreSQL database server
- [x] Deploy platform tag 1.4.3 to all environments
- [x] Create Terraform tag 1.4.4 containing code for creating a postgreSQL database server specific for events 
- [x] Deploy platform tag 1.4.4 to all environments
