### ISSUE TITLE
Replace deprecated Microsoft.Azure.Services.AppAuthentication with Azure.Identity

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#154]
### Description

Microsoft.Azure.Services.AppAuthentication is deprecated. Package should be replaces by [Azure.Identity](https://www.nuget.org/packages/Azure.Identity).

Ref: https://azure.github.io/azure-sdk/releases/deprecated/index.html#net

### Tasks

- [x] Replace package i .csproj file
- [x] Update all use of old package
- [x] QA
- [x] Test

### Acceptance Criterias

- [x] Events project no longer references the deprecated package
- [x] Regression tests are successful
