### ISSUE TITLE
Update event storage endpoint to store generic events to new table

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#156]
### Description

External and App events should both be stored to a new table. events.events (Requires a rename of existing events.events to events_app. #120 )

### Considerations

- Store the full json and index it in the database or store the search values in individual column separate columns for search values
  - If supported, indexing the json document and querying it would lighten the cognitive load for the developers. 
  - jsonb might be the property type to use
  - App events should be stored to both the new and exsisting table.
  - Generic event should be stored only to the new table.

### Specification
- [x] Define the schema for the events table taking all considerations into account. (#99) 
- [x] New auto populated time column for when the event is stored. Used by the cleanup job.
- [x] Adjust the "schema" to exclude the special time column for the event time.

#### Migration script

```sql
CREATE TABLE IF NOT EXISTS events.events (
    sequenceno BIGSERIAL,
    cloudevent JSONB NOT NULL,
    "registeredtime" timestamptz default (now() at time zone 'utc'),
    CONSTRAINT events_pkey PRIMARY KEY (sequenceno)
);

CREATE INDEX IF NOT EXISTS idx_gin_events_computed_cloudevent ON events.events USING GIN (cloudevent jsonb_path_ops);

CREATE INDEX IF NOT EXISTS idx_events_computed_time ON events.events USING btree ("registeredtime" ASC NULLS LAST);

```

#### Measuring performance
Tried out different type of indexing. Gin indexing jsonb column performed as well as search in the original events-table. Support for search on time must be done with own column since jsonb don't include this datatype. 
Created a computed column for time. This will be populated when inserting json in jsonb-column. 
Since convert from text to timestamp is not immutable, we need an own function to do this.

Sql for testing:
``` sql
create or replace function events.to_timestamptz(timestring text) 
returns timestamptz 
language 'plpgsql'
immutable 
as $BODY$
begin
  return timestring::timestamptz;
end;
$BODY$;

CREATE TABLE IF NOT EXISTS events.events_json_computed_column (
    sequenceno BIGSERIAL,
    cloudevent JSONB NOT NULL,
    "time" timestamptz generated always AS (events.to_timestamptz(cloudevent->>'time')) STORED,
	CONSTRAINT events_json_computed_pkey PRIMARY KEY (sequenceno)
);

CREATE INDEX IF NOT EXISTS idx_gin_events_computed_cloudevent ON events.events_json_computed_column USING GIN (cloudevent jsonb_path_ops);

CREATE INDEX IF NOT EXISTS idx_events_computed_time ON events.events_json_computed_column USING btree ("time" ASC NULLS LAST);

select count(*) as count, substring(cloudevent ->> 'source', '(?s).*apps.tt02.altinn.no\/[a-z]*\/[a-z\-0-9]*') as appname from events.events_json_computed_column
where time between '2022-08-01' and '2022-09-01'
group by appname

select cloudevent from events.events_json_computed_column
where cloudevent @> '{"id": "xxxx"}';
```

### Tasks
- [x] Create migration script for creating the new events table
- [x] Set indexes on all query parameters that user can filter events by
- [x] Implement repository method to store the events in the events table 
- [x] Create eventsService to store all events to events table and app events to events_apptable
- [x] Unit tests
- [x] QA

### Testing
- Can be verified by populating the registration queue directly with external events. 
- App events can be generated by using an app in AT that already registers events

### Acceptance Criterias
- [x] It should not be possible to gain access to this endpoint without a PlatformAccessToken
- [x] App events is persisted in both events_app and events table.
- [x] External events are only persisted in the events table
- [x] Indexes exits on the following cloud event properties id, time, subject, source, type

**Comment by vgr** [comment]
Test-report
- internal event added to registration queue is added to both tables.
- external event added to registration queue is added only to events table.
- indexes for tables: 
  - events_app: id, subject, time, source
  - events: computed_time, computed_cloudevent
