### ISSUE TITLE
As an external party I should be able to download specific events directly from the events application

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#165]
### Description

The events application API should provide an endpoint to retrieve a specific event. 
[Open API spec for endpoint available here](https://app.swaggerhub.com/apis/vgrk/altinn-platform_events/v1)

Endpoint:
GET events/api/v1/events?source={source}&id={id}

### Considerations
- Should this endpoint also expose app events? 
  - Yes. App events should be considered a use-case of generic events. Hence, subscriptions and events models should not distinguish between generic (external events) and app events.
- Which scope should be required for retrieving external events?
  - Both `altinn:events.publish` and `altinn:events.subscribe` should give access to this endpoint.
- Should this issue be blocked by authorization?
  - Only if the authorization implementation is close to deployed.
- Should this endpoint be limited to non-PROD environments?
  - Yes, unless feature toggling creates additional issues. The primary need is the get external events to TT02 so it is available for early adopters.

### Dependencies
- [ ] Authorization component must be able authorize external events
- [ ] Schema for events table is defined
- [ ] Existing events table holding appEvents is renamed

### Tasks
- [ ] Rework stored procedure to retrieve event from events database
- [ ] Update service if required
- [ ] Implement endpoint
- [ ] Implement unit tests
- [ ] QA
- [ ] Test
  - [ ] Manual test
  - [ ] Automated test
- [ ] Documentation
  - [ ] Swagger examples? 
  - [ ] Update swagger in docs
  - [ ] User documentation?
- [ ] Update APIM in AT

### Acceptance Criteria
- [ ] An endpoint is exposed for retrieving an event with id
- [ ] Requests without valid bearer token / cookie should result in a 401 response
- [ ] Requests missing scope should result in a 403 response
- [ ] Issue specifying remaining work to set up authorization for endpoint exists and is well defined.

**Comment by SandGrainOne** [comment]
Is this actually needed? Removed from sprint.

**Comment by acn-sbuad** [comment]
I would suggest we close this issue and rather re-open if end users request this functionality.
