### ISSUE TITLE
Create altinn:events scopes and delegation schemes

### ISSUE THREAD

**Issue by vgr** [Altinn/altinn-events#168]
### Description

For events from external producers we should create 2 scopes:
- `altinn:events.publish` - should give access to all operations (POST and GET) on /events
- `altinn:events.subscribe` - should give access to all operations (POST, GET, DELETE, and PUT) on /subscription and GET on /events

These scopes should be open to all for TT02 and other non-PROD environements.
For PROD these should be assigned to service owner and system integrations after contacting Altinn.

### Tasks

- [x] Create scopes in samarbeidsportalen. https://docs.digdir.no/docs/Maskinporten/maskinporten_sjolvbetjening_web.html#opprette-scopes
- [x] Create delegation scheme for these scopes. https://altinn.github.io/docs/utviklingsguider/api-delegering/api-eier/

### Acceptance Criterias

- [x] Scopes created and described so they are available in Samarbeidsportalen.
- [x] Delegation schemes created in Altinn so that these can be delegated.

**Comment by vgr** [comment]
Opprettet scopes `altinn:events.publish` og `altinn:events.subscribe` i VER2.
Har ikke tilgang til å opprette tilsvarende i PROD - utsetter dette til senere. (Lager ny issue)
VER1 er ikke relevant.
