### ISSUE TITLE
Remove unused function GetSubscriptionsExcludingOrg

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#173]
### Description

in #95 the function getsubscriptionsexcludeorgs was made obsolete. This should be droppet from the database.

### Additional Information

drop function if exists getsubscriptionsexcludeorgs(source character varying, subject character varying, type character varying)

### Tasks

- [x] Create migration scrip
- [x] QA
- [x] Test

### Acceptance Criterias

- [x] Function no longer exists in db 
- [x] Push events functionality is unchanged

**Comment by b-brodie-digdir** [comment]
Fixed as a part of #96
