### ISSUE TITLE
Delete obsolete PushController

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#179]
### Description

With #178 the pushController in Events is no longer in use. 
When #178 is deployed to TT02, this endpoint can be deleted. 

### Tasks

- [x] Remove all code related to Push controller
- [x] QA
- [x] Regression test
- [x] Update APIM - ATxx
- [x] Update APIM - YT, TT
- [x] Update APIM - PROD

### Acceptance Criterias

- [x] Regression tests are successful 
- [x] All references to /push and push controller are removed
- [x] Docs updated

**Comment by b-brodie-digdir** [comment]
PR for APIM endringene her
https://dev.azure.com/brreg/altinn-studio-ops/_git/altinn-studio-ops/pullrequest/571

**Comment by SandGrainOne** [comment]
Did some final manual regression testing in at23. Looks good.
