### ISSUE TITLE
Add resource authorization to the POST events endpoint

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#183]
### Description

Initial implementation of events authorization will use hard coded attribute identificators to define correct resource in an authorization request. This is in line with how we currently do it for App events and subscriptions. The resource identifying values will be globally static. The resource registry might be needed in the future if there are authorization parameters that are different across different event producers.

Example of request is defined here: Examples for requests are specified here https://github.com/Altinn/altinn-authorization/issues/42

### Consideration
How do we enable applications to post events? 
Do we need to have strategies for when to require the events.publish scope? 
 - Will we have seperate endpoints but a common service for the rest of the flow? 
 
~~App events will not be handled by the new endpoint. The AccessToken used when authenticating an app will initially not be given the necessary scopes.~~

### Tasks

- [x] Specify resource attributes to specify a resource in an authorization request.
- [x] Implement authorization logic for external events
- [x] Implement unit tests
- [x] QA
- [x] Manual test
- [x] Automated tests	

### Acceptance Criteria

- [x] An end user should not be able to post an event for a source they are not registered to post for
- [x] Posting an event without the resource property should be prohibited
- [x] A request with the altinn:events.publish scope and authorized used should return 201
- [x] A request with the platform access token and an authorized used should return 201

**Comment by acn-sbuad** [comment]
Ready for test. A significant change in this PR is the expected format of the cloud event. Resource should be on format: `urn:altinn:resource:ttd-altinn-events-automated-tests`

**Comment by SandGrainOne** [comment]
The endpoint returns 200 OK and not 201 Created. With that being said we've agreed that 200 Ok is fine in this case. The event is accepted and stored, but we don't have any endpoint to retrieve the specific event. There is nowhere for a 201 Created responss to point to in a Location header.

**Comment by SandGrainOne** [comment]
Removed acceptance criteria:
- [ ] An end user should not be able to post an event type not registered for the event source in the registry
It's no longer true.

**Comment by SandGrainOne** [comment]
Manual testing completed
