### ISSUE TITLE
Replace Microsoft.Extensions.Configuration.AzureKeyVault with new package

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#189]
### Description

Microsoft has deprecated the package Microsoft.Extensions.Configuration.AzureKeyVault. New package is Azure.Extensions.AspNetCore.Configuration.Secrets.

### Additional Information

This job has already been performed on the Storage project in PR https://github.com/Altinn/altinn-storage/pull/79

### Tasks

- [x] Remove the dependency to Microsoft.Extensions.Configuration.AzureKeyVault
- [x] Add dependency to Azure.Extensions.AspNetCore.Configuration.Secrets
- [ ] Update the necessary code for the new package.

### Acceptance Criterias

- [ ] Dependency to Microsoft.Extensions.Configuration.AzureKeyVault has been removed
- [ ] Events still read secrets from KeyVault
- [ ] Events still read secrets from KeyVault into Configuration
- [ ] Regression tests are successful
