### ISSUE TITLE
Execute table name change in production

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#200]
### Description

In #120 the change of the events table to events_app was implemented. This change should be executed in production once the registration queue is established there. 

Release 329 contains the migration script for renaming the table. 
The procedure to roll out the change is as follows: 

- Stop registration function
- Wait until all other queues, inbound, outbound are empty
- Deploy release containing code that goes towards the new table name 
- Once all pods are up and running, start registration function
- Monitor environment for failures. 

### Tasks

- [x] Execute change in Prod-environment (Release-329)

### Acceptance Criterias

- [x] Events are successfully registered and persisted in database
- [x] Events are successfully pushed to subscribers
- [x] GET events endpoint returns expected response for org and party
