### ISSUE TITLE
Remove dependencies to events_app table

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#224]
### Description

After #156 events from Altinn Apps are persisted both in the `events` and `events_app` table.
90 days after this feature is deployed in production the `events` table will contain a copy of every entry in the `events_app` table making this obsolete. 

The goal of this issue is to make the `events_app` table obsolete by re-writing repository  logic (and db procedures / functions if nessecary) to only rely on the `events` table for persisting and retrieving events related to an altinn app. 

## Considerations

- **Should we still keep the differentiation in the service layer for app events and other types of events?** Yes. makes it easier to remove the app layer in the future or allow the two to diverge further. 

Differences in repository input which we will need to address: 
 - **App events supports querying DateTime? from, DateTime? to** (should be easy enough to just add these two into the function. Make sure it's dateTime on the event itself and not the registered time? 
 
 - **App events supports querying a list of sources, events supports querying a single source**
  Should we extend the get events method? Should we create multiple requests, one per source provided? 
### Additional Information

Differences in the two repository inputs will be handled by using a seperate function to retrieve app events.
_No response_

### Tasks
- [x] Update functions/procedures in database
- [x] Manual tests
- [x] Remove writes to app events table
- [x] Automated tests

### Test cases
- [x] Regression tests of GetAppEvents for org
- [x] Regression tests of GetAppEvents for party

### Acceptance Criterias

- [ ] No new app events are persisted in the `event_app` table
- [x] All retrieval of app events goes towards the `events` table
- [ ] Regression tests are successful

**Comment by acn-sbuad** [comment]
Functionality for reading from events table is ready for test now.

**Comment by acn-sbuad** [comment]
Final part of feature ready for test.
