### ISSUE TITLE
Remove obsolete procedures and functions from database

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#226]
### Description

There are some obsolete functions and procedures in the the events database. These should be deleted

### Tasks

- [ ] Set up migration script for deleting obsolete resources
- [ ] QA
- [ ] Manual test

### Acceptance Criterias

- [ ] Event flow is unchanged. 
  - [ ] Events are registered and persisted in DB
  - [ ] Events are successfully retrieved through app/party and app/ {org}/{app} endpoint
  - [ ] Events are successfully pushed to subscribers
