### ISSUE TITLE
Implement use of CloudNative SDK in Functions

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#232]
### Description

In #103 the events component transitioned into using the CloudNative SKD for CloudEvents. 
The functions should do the same. 

Once #103 is deployed to TT02 this feature can be deployed to AT. 

### Tasks

- [x] Replace custom CloudEvents model with SDK model
- [x] Use JsonFormatter for serialization/deserialization
- [x] Update EventClient to send requests using `application/cloudevents+json` content type
- [x] fix serialization& deserialization for cloudenvelope
- [x] fix serialization for SlackEnvelope
- [x] Local testing: ensure push result is still the same
- [x] Unit testing 
- [x] QA
- [x] Manual test

### Acceptance Criterias

- [x] Functions no longer have a separate cloudevent definition

**Comment by acn-sbuad** [comment]
Push events verified in at22. Format still the same.
