### ISSUE TITLE
Add a mechanism for Events Function to reuse AccessTokens

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#241]
### Description

Event functions are currently performing many thousand requests against KeyVault every day. The goal with this issue is to implement a mechanism so that a generated AccessToken can be reused for as long as it is valid.

It should be possible do to this by implementing a service to be registered as a singleton: https://www.rahulpnath.com/blog/dependency-injection-in-azure-functions/#understanding-azure-function-service-lifetimes

Initial idea is to create a new class to work as an AccessTokenProvider. The class should hold on to and provide the same AccessToken as long as it is valid. It should then automatically create a new one. The function app should have a single instance of the service across multiple calls.

### Tasks

- [ ] Consider changing the lifetime of AccessTokens generated by EventsFunction to be longer than default.
- [ ] Build a new AccessTokenProvider class that can hold on to an access token for as long as it is valid and then create a new one when needed.
- [ ] Change EventsRegistration function to use the new provider.
- [ ] Change EventsOutbound function to use the new provider.
- [ ] Change EventsInbound function to use the new provider.
- [ ] Create and Update tests as needed.
- [ ] Add extra logging that can be used to analyse whether a singleton service is actually reusable.
- [ ] Cleanup logging once we've assured that the mechanism works.

### Acceptance Criterias

- [ ] AccessTokens are reused across multiple calls to Events.

**Comment by codemascot** [comment]
This issue is blocked by this issue: https://github.com/Altinn/altinn-accesstoken/issues/81

Also need to have it's own `ISigningCredentialsResolver` (from `altinn-accesstoken`) implementation to resolve the signing credentials.
