### ISSUE TITLE
Drop obsolete function insert_subscription 

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#253]
### Description

In #96 a new function `events.insert_subscription` accepting the hashed sourcefilter was introduced. The obsolete function that does not accept the hashed source filter as input should be dropped once #96 is deployed and running in all environments.

### Tasks

- [x] Create migration script for dropping function
- [x] QA
- [x] Regression test of subscription functionality

### Acceptance Criterias

- [x] Only one function `events.insert_subscription` exists in the database

**Comment by acn-sbuad** [comment]
verified ok in at22
