### ISSUE TITLE
Add resource authorization to the POST subscriptions endpoint

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#259]
### Description
Blocked by #315 

During development of #107 authorization was left out. This should be implemented.

### Considerations
- How do we prevent subscriptions being set up with e.g. scope that cannot be validated during push events? 
Scopes are available during creation of subscription, but after the fact this isn't something that the authorization component will be aware of. **Leave it to team auth to control what policies are set up and what properties are utilized?** 

- do we require an exact match for the resourceFilter? **Yes**

- do we support end user authorization for generic events now? 
  - [ ] End user with required role for subscribe events should be allowed to subscribe to generic events
  - [ ] End user without required role for subscribe should not be allowed to subscribe to generic events
### Tasks
- [x] Extend subscriptionRequest model to include resource filter (optional)
- [x] Add resourceFilter requirements for Generic controller validation
- [x] Implement authorization logic in AuthorizeSubscription in GenericSubscriptionService
- [x] Unit tests
- [x] Manual tests
- [x] Automated tests

### Acceptance Criterias

- [x] ResourceFilter is required for generic event subscriptions
- [x] Org with subscribe rights for events should be allowed to subscribe to generic events
- [x] Org without subscribe for events should not be allowed to subscribe to generic events
- [x] Org with read rights for events should be allowed to subscribe to app events
- [x] Org without read events should not be allowed to subscribe to app events
- [x] It should not be possible to create a subscription for a resource that doesn't exist in the resource registry
- [x] End user with required role for subscribe events should be allowed to subscribe to app events
- [x] End user without required role for subscribe should not be allowed to subscribe to app events

**Comment by SandGrainOne** [comment]
Testing completed ok.
