### ISSUE TITLE
Delete obsolete getsubscriptions function

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#278]
### Description

A new function `events.getsubscriptions ` accepting a list of hashed source filters was introduced. The obsolete function that does not accept the hashed source filter as input should be dropped once new function is deployed and running in all environments.

### Tasks

- [x] Create migration script for dropping function
- [x] QA
- [x] Regression test of push events functionality

### Acceptance Criterias

- [x] Only one function `getsubscriptions` exists in the database

**Comment by acn-sbuad** [comment]
verified ok in at22
