### ISSUE TITLE
Set up events use-case tests for AT in GitHub

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#285]
### Description

Building on the output of issue #166. This issue should focus on getting the tests to run scheduled with the help of github actions.

### Tasks

- [x] Define environment and environment variables for workflows running from Events
  - [x] AT21
  - [x] AT22
  - [x] AT23
  - [x] AT24
- [x] Create a slack hook that can be used to publis alerts to slack.
- [x] Define a workflow in github to run the use-case tests for Events

### Acceptance Criterias

- [ ] Use-case tests are started once every 15 minutes.

**Comment by acn-sbuad** [comment]
Look into a github app for the triggering task as OAuth token is the only way to authenticate towards the workflow without using a PAT at the time.
