### ISSUE TITLE
Trigger full set of tests of Events after a deploy

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#286]
### Description

As a part of the release pipeline for Events we want to run the full set of tests to verify Events after deploy. There needs to be a delay to ensure that the new version is the active version of the application.

### Tasks

- [ ] Extend release pipeline to trigger the Events tests in correct environment.
   - [ ] This requires a github access token so that DevOps can run a github workflow.
- [ ] The release pipeline should fail if the tests fail.
- [ ] The workflow should send a message to slack alert-info
- [ ] Remove outdated tests from altinn.studio repository
- [ ] Remove outdated k6-test pipeline dependencies to Events.

### Acceptance Criterias

- [ ] Tests are triggered shortly after deploy.

**Comment by acn-sbuad** [comment]
duplicate created in #473. Closing this as the other one is in progress
