### ISSUE TITLE
Add indexes to generic `events` table

### ISSUE THREAD

**Issue by b-brodie-digdir** [Altinn/altinn-events#292]
### Description

To ensure acceptable performance with millions of records in the `events` table, we should add indexes to certain properties in the jsonb column `cloudevent` which are used by queries. 

Suggested columns:
- `subject` / `source` / `type` / `after` 

### Considerations

Which index? 

- GIN
- GIN Index “pathops”: only operator support is the “@>” 
  -  The technical difference between a jsonb_ops and a jsonb_path_ops GIN index is that the former creates independent index items for each key and value in the data, while the latter creates index items only for each value in the data
- ~~B-tree~~ Essentially, this can only be used for whole object comparisons, which has a very limited use case.

#### Insert 324943  events
Baseline
Query returned successfully in 1 min 11 secs.

GIN Index on id, subject, source and type
Query returned successfully in 1 min 37 secs.

Hash Index on id, subject, source and type
Query returned successfully in 1 min 13 secs.

## Conclusion

Querying for events in the table with various indexes vs baseline does not give any effect. 
Only the existing index for `idx_gin_events_computed_cloudevent` is utilized when calling the get events function. 

We have however, identified some changes to the function to make the overall performance better.

Modified query for retrieving events 

```sql

AS $BODY$

BEGIN
return query
SELECT cast(cloudevent as text) as cloudevents
	FROM events.events
	WHERE (_subject IS NULL OR cloudevent @> (select '{"subject": "' || _subject || '"}')::jsonb )
	and (_alternativeSubject IS NULL OR cloudevent @> (select '{"alternativesubject": "' || _alternativeSubject || '"}')::jsonb )
	AND (_type IS NULL OR cloudevent->>'type' ILIKE ANY(_type) )
	AND (_source IS NULL OR cloudevent->>'source' ILIKE ANY(_source))
	AND (_after = '' OR sequenceno >(
		SELECT
			case count(*)
			when 0
				then 0
			else
				(SELECT sequenceno
				FROM events.events
				WHERE cloudevent @> (select '{"id": "' || _after || '"}')::jsonb 
				ORDER BY sequenceno ASC
				LIMIT 1)
			end
		FROM events.events
		WHERE cloudevent @> (select '{"id": "' || _after || '"}')::jsonb ))
  ORDER BY sequenceno
  limit _size;
END;
$BODY$;
```

### Tasks:
- [ ] Test current `insert` and `get` performance before adding indexes (baseline)
- [ ] Add indexes
  - [ ] Consider which column (if any) should have a clustered index.
- [ ] Repeat performance tests and document impact of new indexes.
