### ISSUE TITLE
Add resource authorization to the GET events endpoint

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#295]
### Description

During development of https://github.com/Altinn/altinn-events/issues/108 authorization was left out. This should be implemented.

Examples for requests are specified here https://github.com/Altinn/altinn-authorization/issues/42

### Considerations 

- [x] Naming of subject attributeIds. If these are to be directly picked from the claims in the claims principal we must have another look at the naming of the attributes in the examples of altinn/altinn-authorization#42. 
  - `urn:altinn:orgnr`: claim in claimsprincipal is `urn:altinn:orgNumber`
  - `urn:altinn:apiscope`
- How do we handle authorization of end users. What is included in the policy and what are we required to include in the xacml request? 
  - [x]   Authorization component should be able to handle this when we provide resource and resourceId. 

### Tasks

- [x] Extend authorization service
- [x] Manual test
  - [x]  org requests
- [x] Automated tests
  - [x] Define resource in resource registry for automated testing
  - [x] Update event in testdata
- [x] QA
- [x] Documentation

## Testing 

- We have created a policy for the resource `ttd-altinn-events-automated-tests` org `ttd` has publishing and subscribing rights to events under this resource. 

### Acceptance Criterias

- [x] If authorization token is missing response should be 401
- [x] If authorization token is missing scope altinn:events.subcribe response should be 403
- [x] If authorization token represents another org than ttd response should be 403
    - The result is an empty list. Expected? Yes, the events are filtered based on authorization and removed from the list. 
    - We will consider returning 403 when support for specific resource is being added.
- [x] If authorization token represents an end user response should be 403
- [x] If authorization token represents org ttd and contains scope altinn:events.subcribe response should be 200
