### ISSUE TITLE
Send use case test results and metrics to Grafana

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#296]
### Description

Use case tests for events runs in Github Workflows. We would like to forward the test results and/or metrics to Grafana so they can be observed over time. 

Urls might change from test to test as IDs might be included, but they are testing the same thing and we would like to be able to group and/or compare the results. How can this be acheived? 

### Tasks

- [ ] Define parameter setup required to be able to forward test results to Grafana
- [ ] 	Define dashboard structure. Which results should be grouped togheter? 
- [ ] 

### Acceptance Criterias

- [ ] Test results and metrics are available in Grafana
- [ ]
