### ISSUE TITLE
Set up events use-case tests for TT/Prod in GitHub

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#300]
### Description

Extracted from #285

Required maskinporten setup: 
Client to be set up in test and prod 

Scopes: altinn:events.publish, altinn:events.susbcribe, altinn:serviceowner

Follow doc: https://docs.altinn.studio/technology/solutions/cli/configuration/maskinporten-setup/
base64 encoded jwk should be added as an action secret to the repository. 

### Tasks
- [x] Create altinn:events.publish, altinn:events.susbcribe scopes in production
- [x] Set up maskinporten client
  - [x] tt02
  - [x] PROD
- [x] Define environment and environment variables for workflows running from Events
  - [x] TT02
  - [x] Prod
- [x] Create client integration in maskinporten for digdir prod with scope: 
- [x] Register use case test resource in resource registry in prod
- [x] Create workflow file for prod
- [x] Clean up the use-case pipeline(s) to skip the Events tests
- [x] Remove unused env secrets in tt02  partyid, userid, personnumber

### Acceptance Criterias

- [x] Use-case tests are started once every 15 minutes.
- [x] Message in Slack sumarizes failed checks

**Comment by annerisbakk** [comment]
@acn-sbuad Er det noe som gjenstår her?

**Comment by acn-sbuad** [comment]
Ja, det er vel ingen workflow oppe og kjøre enda da vi ventet på klient. Ser denne er på plass nå, så denne bør jo være klar til å jobbes videre med. Bør være løst på max 3-4 timer. @annerisbakk

**Comment by annerisbakk** [comment]
@acn-sbuad Kan den defineres som "Up-for-grabs"?
