### ISSUE TITLE
Add resourceFilter attribute for all subscriptions

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#315]
## Description 
Resource will be our way of identifying apps and other resources moving forward. To make this process easier from subscriptions we require a resource filter for all existing and new subscriptions. 

## Considerations
- Only AT environments might have subscriptions based on a source that isn't on the app domain. 

## Deployment
 - [x] Deploy migration script that introduces resourceFilter column for subscription table
 - [x] Deploy feature where resource filter is set for all app subscriptions
 - [x] Deploy feature where resource filter is required for generic subscriptions
 
After deployment of migration scripts:
 - [x] Run manual script for modifying existing existing subscription without resource filter
   - [x] 	Cannot be a part of migration script at altinn host must be defined per environment

In a later release: 
- [x] Deploy migration script dropping old insert_subscription, get_subscription & find_subscriptions function 

### Check what resource filter will be
```sql
SELECT sourcefilter, 
CONCAT('urn:altinn:resource:altinnapp.', 
    SPLIT_PART(sourcefilter, '/', -2) ,
    '.', 
    SPLIT_PART(sourcefilter, '/', -1)) AS resourcefilter
FROM events.subscription
where sourcefilter like CONCAT('https://%.apps.', 'at22.altinn.cloud', '/%') 
and resourcefilter IS NULL;
```

### Add new column
```sql
ALTER TABLE events.subscription ADD COLUMN resourcefilter character varying;
```

### Add column value
```sql
update events.subscription
set resourcefilter = CONCAT('urn:altinn:resource:altinnapp.', 
    SPLIT_PART(sourcefilter, '/', -2) ,
    '.', 
    SPLIT_PART(sourcefilter, '/', -1)) 
where sourcefilter like CONCAT('https://%.apps.', 'at22.altinn.cloud', '/%') 
and resourcefilter IS NULL;
```

## Task
- [x] Ensure all app subscriptions are given a resourceFilter attribute upon creation, if it doesn't exists
- [x] Require resource filter for all subscriptions on generic events
- [x] Implement unit tests 
- [x] Manual test locally
- [x] Run manual db script
  - [x] AT
  - [x] YT
  - [x] TT
  - [x] PROD
- [x] Ensure all existing subscriptions in database have a resource filter property
- [x] QA
- [ ] Manual test

## Test cases
- Post subscription for app resource: resourceFilter included in response object and persisted in DB.
- Post subscription for generic resource: resourceFilter included in response object and persisted in DB.
- Post duplicate subscription: same subscription id returned
- Post almost identical subscription, everything but resource identical: new subscription id returned
- Get subscription by id: resourceFilter included in response object
- Get subscription by consumer: resourceFilter included in response
- Verify that events are pushed to subscription that have matching source filter. Support for matching on resource will be developed later

## Acceptance criteria
- [x] All Subscriptions have a resourceFilter attribute defined in the database 
- [x] When an app subscription is posted,  a resourceFilter should be generated based on the source filter
- [x] A subscription for an "unknown" event source should always require a resourceFilter

**Comment by acn-sbuad** [comment]
Ready for testing in AT. 
Remaning dev tasks are related to the manual work that needs to be done after deploy to an environment.

**Comment by SandGrainOne** [comment]
Testing completed for now. Created two issues and one open question.

1. #351 
2. #352 
3. It's possible to create subscriptions for events from an non existent resource. Is this handled by a separate issue?
