### ISSUE TITLE
Extend GET endpoint to include resource as query param

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#316]
### Description

Two new properties: resource and resourceId have been defined for cloudEvents processed through Altinn. 
Event subscribers should be able to request a list of events based on the resource attribute. 

### Consideration
- Do we need to use source as a query parameter once resource is required? 
  - No, support for source, will be removed as query param. 
- Consider if we need to check if after is defined in function

### Tasks
- [x] Add new required query parameter to endpoint
- [x] Remove support for source as query parameter
- [x] Update function in postgreSQL to match on resource and remove support for source
- [x] Update function to use optimal queries for jsonb 
- [x] QA
- [x] Update swagger
- [x] Test
- [x] [Documentation](https://github.com/Altinn/altinn-studio-docs/pull/1167)

### Acceptance Criteria
- [x] It is possible to query events using the resource query parameter
- [x] A request without resource parameter should fail with bad request
- [x] A request with resource and after parameter is valid
- [x] Indexes are utilized when getevents function is called.
- [x] ~~Querying app events should also utilize resource, if not possible to consolodate procedures ensure seperate issues is created~~ Moved to seperate issue

**Comment by SandGrainOne** [comment]
There are no index on resource.
