### ISSUE TITLE
Include resource attribute to existing app events in db

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#336]
## Description

All cloudevent entries in the events table should include the resource property. 
and resource instance.

Some numbers. 
performance has not been in focus. Locally when updating 324946 rows takes 30 sek. 

## Sql

```sql
# Check count for events without resource

select count(1)
FROM events.events
WHERE cloudevent->>'source' LIKE CONCAT('https://%.apps.', 'tt02.altinn.no', '/%')
  AND cloudevent->>'resource' IS NULL;

```

```sql
# Check what resource will be
SELECT sequenceno, cloudevent->'source', 
CONCAT(
	'"',
	'urn:altinn:resource:altinnapp.', 
    SPLIT_PART(cloudevent->>'source', '/', -5) ,
    '.', 
    SPLIT_PART(cloudevent->>'source', '/', -4),
	 '"') AS resource,
CONCAT( 
	'"',   
	SPLIT_PART(cloudevent->>'source', '/', -2) ,
    '/', 
    SPLIT_PART(cloudevent->>'source', '/', -1),
	'"') AS resourceinstance
FROM events.events
WHERE cloudevent->>'source' LIKE CONCAT('https://%.apps.', 'tt02.altinn.no', '/%')
  AND cloudevent->>'resource' IS NULL;
```

```sql
# generate copy of table for testing

CREATE TABLE events.events2 AS 
TABLE events.events;

```
```sql

# add extension attributed to event
WITH eventstemp AS (
  SELECT sequenceno, 
    CONCAT(
      '"',
      'urn:altinn:resource:altinnapp.',
      SPLIT_PART(cloudevent->>'source', '/', -5),
      '.',
      SPLIT_PART(cloudevent->>'source', '/', -4),
      '"') AS resource,
    CONCAT(
      '"',
      SPLIT_PART(cloudevent->>'source', '/', -2),
      '/',
      SPLIT_PART(cloudevent->>'source', '/', -1),
      '"') AS resourceinstance
  FROM events.events
  WHERE cloudevent->>'source' LIKE CONCAT('https://%.apps.', 'tt02.altinn.no', '/%')
    AND cloudevent->>'resource' IS NULL
)
UPDATE events.events
SET cloudevent = jsonb_set(cloudevent, array['resource'], eventstemp.resource::jsonb) ||
                jsonb_set(cloudevent, array['resourceinstance'], eventstemp.resourceinstance::jsonb)
FROM eventstemp
WHERE events.events.sequenceno = eventstemp.sequenceno;
```
## Task
- [x] Generate SQL
- [x] QA
- [x] Manual test locally
- [x] Run script in AT21
- [x] Run script in AT22
- [x] Run script in AT23
- [x] Run script in AT24
- [x] Run script in TT02
- [x] Run script in YT01
- [x] Run script in PROD

## Execution
AT: <70k events in each environment update tok <10 seconds. 
TT02: 308777 events - 1min 15 sec
YT01: 1375887 events, modified script to update batches of 100k events as a time. Each batch took about 1 min. 
## Acceptance criteria
- [ ] There are no events in db without resource property.

**Comment by SandGrainOne** [comment]
In the second code block:
```
# Check what resource will be
SELECT sequenceno, cloudevent->'source', 
```
I assume it needs a second > character?
```
SELECT sequenceno, cloudevent->>'source', 
```

**Comment by acn-sbuad** [comment]
1. The second code block is only to display the contents of the source. As we won't be working further with it or putting it into a column defining a strict type the second '>' is not required. 

2. Yes, so this is just to create an exact copy for the event table if we want to test the script before executing it on the real event table, as it cannot have a duplicate name.

Only 3rd code block is required to make the update in the environments.
