### ISSUE TITLE
Upgrade Events functions to dotnet v8.0

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#393]
### Description

We need to upgrade events function to target dotnet v8.0. This is important as some of the dependencies being updated leads to version conflicts.

An other important change is to have the functions run in isolated mode.

### Additional Information

This has been tested and seems to run fine in the FileScan function.

### Tasks

- [ ] Change target framework for the Events functions project. Fix conflicts as they appear.
- [ ] Ensure that the functions are running in isolated mode. 
- [ ] Update terraform scripts to ensure the function run in isolated mode. (If needed).
- [ ] Plan a controlled redeploy if necessary to avoid downtime.

### Acceptance Criterias

- [ ] All functions are triggered correctly and run without issues in isolated mode.

**Comment by acn-sbuad** [comment]
related to #478
