### ISSUE TITLE
Remove GeneralSettings__EnableExternalEvents setting and guard in controller

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#442]
### Description
Enable generic events in production by removing the feature toggle.

### Tasks
- [x] Remove the code controlling the generic events feature
- [x] Remove the value from environment settings in values.yml
- [x] QA
- [x] Manual test
- [ ] Documentation

### Acceptance criteria
- [x] It's possible to publish generic events in production
- [x] It's possible to subscribe to generic events in production
- [x] It's possible to use the API endpoint to GET generic events in production
