### ISSUE TITLE
Set up regression test workflows

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#473]
### Description

Regression tests should be executed after every new deployment of the events component. 
The workflow should be hosted in this github repository and triggered as a part of the release pipeline in Azure DevOps. 

Storage and notifications already have this set up and can be used as inspiration. 

### Tasks

- [x] Set up workflow for regression test AT
- [x] Set up workflow for regression test TT
- [x] Set up workflow for regression test Prod
- [x] Set up trigger of workflow from AzDO release pipeline
- [x] QA
- [x] Manual testing
- [x] Remove trigger for AzDo regression test pipeline in TT and Prod
- [x] Ensure release fails if trigger of workflow fails
- [x] delete k6 tests from studio repo

### Acceptance Criterias

Regression tests are executed after each new deployment
