### ISSUE TITLE
When event subject is an organization, the alternative subject filter prefix needs to be `/organisation/`

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#474]
### Description

Alternative subject is currently using prefix `/org/` for when an organisation is the subject of an event. In almost all other contexts `/org/` will refer to an application owner and not a party. This difference can lead to confusion.

When the subject of an event is an organisation, the prefix should instead be `/organisation/`.

### Tasks

- [x] Update alternative subject handling to support `/organisation/` (Keep support for `/org/`)
- [x] Update documentation to suggest that subscribers use the new format in their alternative subject filter
- [x] Change review
- [ ] Manual testing

### Acceptance criteria

- [ ] When creating a subscription with alternative subject filter on the format `/org/{no}` the subscription is stored with correct party id value
- [ ] When creating a subscription with alternative subject filter on the format `/organisation/{no}` the subscription is stored with correct party id value
- [ ] Documentation reflects the new preferred format
