### ISSUE TITLE
Change altinn-env-events-fa functions to target dotnet 9

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#478]
### Description

We need to upgrade events function to target dotnet v9.0. This is important as some of the dependencies being updated leads to version conflicts.

An other important change is to have the functions run in isolated mode.

### Tasks
- [ ] Update terraform scripts to enable dotnet 9 for the events functions
- [ ] Deploy the tf changes
- [x] Change target framework for the Events functions project. Fix conflicts as they appear.
- [x] Ensure that the functions are running in isolated mode. 
- [ ] Update terraform scripts to ensure the function run in isolated mode. (If needed).
- [ ] Plan a controlled redeploy if necessary to avoid downtime.

### Acceptance Criterias

- [ ] All functions are triggered correctly and run without issues in isolated mode.

**Comment by acn-sbuad** [comment]
Seems there still isn't support for cusom queue processor logic in Isolated workers ref https://github.com/Azure/azure-functions-dotnet-worker/issues/382.
We cannot upgrade to isolated function until we get this support or a workaround. And as .net 8 is dependent on an isolated worker, this upgrade is blocked too.

**Comment by olebhansen** [comment]
Seems .net 8 now is supported in-process: https://github.com/Azure/azure-functions-host/issues/9951

**Comment by olebhansen** [comment]
Do assesment if this is needed to retain support short term, or if we can refactor onto a service-bus implementation.
