### ISSUE TITLE
Incorrect resource format used for Altinn app events

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#495]
### Description of the bug

Resource is currently set to urn:altinn:resource:altinnapp.{org}.app 
correct format is urn:altinn:resource:app_{org}_{app}

### Steps To Reproduce

Check db for event resource and subscription resourcefilter. 

### Tasks

__Before__
  - [x] Notify externally about a 15 min "gap" in push of events and changed format of resourceId

__During__
  - [x] Notify "vakt" that alerts might occur
  - [x] Stop EventsRegistration function
  - [x] Verify that EventsInbound poision queue is empty
  - [x] Deploy events changes ( #494 )
  - [x] Run db script to alter subscription and events table
  - [x] Deploy new EventsRegistration function that alters resourceid for app events  ( #494 )
  -  [x] Start EventRegistration function
 
__Verification__
- [x] Create subscription and confirm events are received
- [x] Pull events and confirm correct resource format

__After__

  - [x] Update all examples and references to resource in docs: https://github.com/Altinn/altinn-studio-docs/pull/1566
