### ISSUE TITLE
Atomic events

### ISSUE THREAD

**Issue by olebhansen** [Altinn/altinn-events#570]
Epic for the topic of having sequential and non-duplicated events.

### Additional information
The following link is to a blog post where the author has a few throughts and ideas for how to handle the issue we have with missing events:

https://blog.sequinstream.com/postgres-sequences-can-commit-out-of-order/

```[tasklist]
### Tasks
- [ ] (https://github.com/Altinn/altinn-events/issues/333)
- [ ] https://github.com/Altinn/altinn-events/issues/307
- [ ] https://github.com/Altinn/altinn-events/issues/322
```

**Comment by SandGrainOne** [comment]
The following link is to a blog post where the author has a few throughts and ideas for how to handle the issue we have with missing events:

https://blog.sequinstream.com/postgres-sequences-can-commit-out-of-order/
