### ISSUE TITLE
Start collecting telemetry for subscription handling

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#602]
### Description

Introduce telemetry for key elements ragarding the subscription handling. We want to know how much time it takes to process subscriptions for an event and whether subscriptions are valid. Meaning if the consumer is still allowed to subscribe to the event it was created for.

This issue assumes that we already have OpenTelemetry turned on and that there are other telemetry already being registered. If this is not the case the issue would require more tasks for setting up the framework for using OpenTelemetry.

### Additional Information

This issue where created during issue cleaning where #15 came up. We want to collect more data about the possible issue before taking any actions.

### Tasks

- [ ] Consider what type of metrics to use for each of the metrics below. e.g counter or rate
- [ ] Create a metric for how long it takes to process an event for subscribers
- [ ] Create a metric for the amount of failed authorizations when checking subscriptions
- [ ] Create a dashboard to visualize the matrics

### Acceptance Criterias

- [ ] We can see the two new metrics on a dashboard in /monitor/. 

```[tasklist]
### Dependencies
- [ ] https://github.com/Altinn/altinn-profile/issues/225 (will provide generic OTEL learnings/inputs)
```
