### ISSUE TITLE
Upgrade Events to dotnet v9

### ISSUE THREAD

**Issue by hggutvik** [Altinn/altinn-events#622]
### Description

We should upgrade the Events application to .net9. .net9 has standard time support until May 12, 2026, but we should take the time to upgrade and not wait for .net 10. 

### Additional Information

[.NET Core Support lifecycle](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)
[Container Patching](https://pedia.altinn.cloud/altinn-3/ops/patching/containers/#net-core)

### Tasks

- [x] Update base images in the dockerfile for .net9
- [x] Bump all projects; src and test, to .net9
- [x] Update any build pipelines to support .net9
- [x] Update any github workflows with .net9
- [ ] Check if we need to change anything in SonarCloud

### Acceptance Criterias

- [ ] Events is built with .net9 tooling and run on .net9

**Comment by hggutvik** [comment]
This upgrade has been implemented in some other repos - might give some clue to what needs to be done here as well:
https://github.com/Altinn/altinn-profile/issues/261
https://github.com/Altinn/altinn-notifications-email/issues/110
https://github.com/Altinn/altinn-notifications-sms/issues/76

**Comment by sigridbra** [comment]
Cannot upgrade Events.Functions yet- Separate issue here: https://github.com/Altinn/altinn-events/issues/478
