### ISSUE TITLE
Create a job to delete events older than 90 days

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#8]
### Description

Events are primarily fresh data that we don't want to store indefinitely.

Scheduled cron job directly in PostgreSQL:
https://www.citusdata.com/blog/2016/09/09/pgcron-run-periodic-jobs-in-postgres/

### Acceptance Criterias

All events in database newer than 90 days

### Tasks
- [x] Enable extension pg_cron
- [x] Create cron-job, run every night 3 am
- [x] Update terraform scripts to include the extension
- [x] Verify cleanup

**Comment by tba76** [comment]
pg_cron is only available in flexible server. 
Script ready in branch feature/8-cleanup-old-events-cron
