### ISSUE TITLE
Timeout exceptions in NpgSQL connection

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-events#86]
### Description of the bug

	We see an increased number of timeout exceptions for events. 16th and 17th august

### Steps To Reproduce
Check logs to see error. 

Locally, add a `PERFORM pg_sleep(35);` in a function to simulate a slow query.

### Additional Information

[PR](https://dev.azure.com/brreg/altinn-studio-ops/_git/altinn-studio-ops/pullrequest/482)

### Tasks
- [x] Set temporary timeout for TT and PROD
- [x] Consider need for increased timeout after index is created. 
  -  Query times well without default timeout
- [x] Remove temporary timeout if its no longer required

**Comment by acn-sbuad** [comment]
Timeout rolled out in TT/Prod. Immediate reduction in failed requests from SKD. Next step is to consider removing it after index is introduced
