### ISSUE TITLE
Unify source filters for person- and organization-subscription

### ISSUE THREAD

**Issue by vgr** [Altinn/altinn-events#95]
#### Discussion
Currently, fetching the correct person- and organization-subscription is handled slightly differently.

When an event is pushed, a person subscription query is created based on the source URI.
The source is shortened to only include the 2 first path segments of the URL.
Ex: https://ttd.apps.altinn.cloud/ttd/apps-test/instances/123 -> https://ttd.apps.altinn.cloud/ttd/apps-test
This source is then used in PostgreSQL to find subscriptions equal to https://ttd.apps.altinn.cloud/ttd/apps-test

Pros:
- Matching is handled by the DB
  
Cons:
- Only works for Altinn Apps and other source filters that use exactly 2 path segments. will need to be changed to support external apps.

When an event is pushed the organization query does not take into account the source when fetching subscriptions.
Instead this is handled by the code afterwards.

Pros:
- Easily extendable to new URI schemes.
- Source matching is done correctly for URL path segments. (Ref: Issue #25) This is not currently an issue for the other approach, but care needs to be taken when new schemes are supported.

Cons:
- DB result contains all subscriptions. Performance/scalability

#### Expected behaviour:
| event source | event source filter | match? |
| --- | --- | --- |
| https://host.com/a/b/c    | https://host.com/a/b      | yes |
| https://host.com/a/b      | https://host.com/a/b      | yes |
| https://host.com/A/B      | https://host.com/a/b      | ? |
| https://host.com/a/b/c    | https://host.com/a/b/b    | no |
| https://host.com/a/bb     | https://host.com/a/b      | no |
| https://host.com/a/b      | https://host.com/a/bb     | no |
| https://host.com/a/b      | https://host.com/a/b/c    | no |
| https://host.com/a         | https://host.com/a          | not legal  (#96)|

#### Proposed solution
- Use DB matching for all subscriptions
- Consolidate both SQL functions into 1 that retuns both orgs and consumer subscriptions.

The implementation of the SQL function should take into account #96, so we don't need to re-implement it entirely.

### Additional Information
Support for arbitrary URLs have been moved to a new issue #96 

### Tasks

- [x] Ensure that stored data is in lower case
- [x] Ensure that filter values used in where clause  is lower case
- [x] Create unified function to identify subscriptions that should receive an event through push
- [x] Update repository logic as needed
- [x]  Review/QA
- [x] Unit tests
~~- [ ] Documentation~~
(Automated tests moved to separate issue #166 )

### Acceptance Criteria

- [x] Changes should not affect the functionality, no breaking change
- [x] Matched subscriptions are identified across all consumer types

**Comment by SandGrainOne** [comment]
@vgr Jobber litt videre med saken.

**Comment by acn-sbuad** [comment]
Test
prepare in npgsql + positional parameters. 
Position = 1

**Comment by acn-sbuad** [comment]
This logic might work: 
let filterArray = regexp_split_to_array(s.sourcefilter);
let sourceArray = regexp_split_to_array(source)
let a = array_length(filterArray);
let b =  array_length(sourceArray);

select * from subscription where 
where a < b
and foreach(i = 0 : a){
sourceArray[0]== filterArray[0]
}

**Comment by vgr** [comment]
That algorithm will work, but I wonder if it will be harder to scale as the subscription table increases.
I think. the critical section is:
`where a < b 
and foreach(i = 0 : a)
{
	sourceArray[0]== filterArray[0]
}`
vs
`where position(s.sourcefilter in source) = 1)`
(The splitting of arrays vs transforming into match-format should be neglible compared to this.)

My hypothesis is that if we have a large number of apps, which all have source filters a = [org, appname], this will be less performant with a for-loop comparing all subscriptions. However, I am far from certain since I haven't looked at how position is implemented/optimized, or how PostgreSQL can optimize the loop. (Would be cool to test this :))

I agree that this is more readable and easier to maintain, so if the SQL performance of these two statements are comparable for large numbers such as 100 000 subscriptions, I think we should consider it. We don't have to implement it with performance in mind right away, but we be nice to not have to change it as well.

I think we should discuss this further.
