### ISSUE TITLE
Add support for external URL and URN source subscriptions

### ISSUE THREAD

**Issue by vgr** [Altinn/altinn-events#96]
### Implementation
See proof-of-concept: https://dotnetfiddle.net/DP2nY8
1. Create a hash of the subscription source filter. -> New column in DB table.
2. When getting all matching subscriptions for an event we can create a set of hashes - one hash for each substring of the event source.
    - "www.host.com/a/b/c/d/e" -> `[ hash("www.host.com"), hash(""www.host.com/a"), hash("www.host.com/a/b", ...]`
    - Can trim `\` from URLs
    - Can use SHA, unless we find a better alternative 
3. SQL function can then use  `WHERE subscription.source IN hash-set`, which allows us to use b-tree index on the hash-column.

### Tasks

- [x] Add new column to subscription table and create an index for this
- [x] Decide algorithm and create hash function
  - MD5 Hash is used by PostgreSQL 
- [x] Generate hash for all existing subscriptions and fill column with values (all environments)
- [x] Update POST subscription endpoint to store hashes when new subscriptions are stored
- [x] Update push to use hashes for subscription-lookup
- [x] Documentation
- [x] Testing

### Acceptance criteria
- [x] Subset matches should not occur. 
- [x] All subscriptions have a new populated colum sourcefilterhash in db 
- [x] Happy path should work as expected: push events
- [x] New subscriptions should have sourcefilterhash populated in db

**Comment by vgr** [comment]
Alternative implementation: https://dotnetfiddle.net/DP2nY8
The hash-set should be more compatible with B-tree indexes since the query can use the IN-operator.
