### ISSUE TITLE
Postgres jsonb - events

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-events#99]
### Description

When upgrading to flexible server, newer versions of Postgres is available.
We should consider using jsonb to store cloudevents.
"jsonb data is stored in a decomposed binary format that makes it slightly slower to input due to added conversion overhead, but significantly faster to process, since no reparsing is needed. jsonb also supports indexing, which can be a significant advantage."
[Documentation jsonb](https://www.postgresql.org/docs/current/datatype-json.html)

### Tasks

- [x] Install PostgreSQL locally (newest version available in Azure)
- [x] Create table for events with jsonb datatype
- [x] Create different indexes for search
- [x] Measure performance (populate existing table and compare searchs?)

**Comment by tba76** [comment]
### Measuring performance
Tried out different type of indexing. Gin indexing jsonb column performed as well as search in the original events-table. Support for search on time must be done with own column since jsonb don't include this datatype. 
Created a computed column for time. This will be populated when inserting json in jsonb-column. 
Since convert from text to timestamp is not immutable, we need an own function to do this.

Sql for testing:
``` sql
create or replace function events.to_timestamptz(timestring text) 
returns timestamptz 
language 'plpgsql'
immutable 
as $BODY$
begin
  return timestring::timestamptz;
end;
$BODY$;

CREATE TABLE events.events_json_computed_column (
    sequenceno BIGSERIAL,
    cloudevent JSONB NOT NULL,
    "time" timestamptz generated always AS (events.to_timestamptz(cloudevent->>'time')) STORED,
	CONSTRAINT events_json_computed_pkey PRIMARY KEY (sequenceno)
);

CREATE INDEX idx_gin_events_computed ON events.events_json_computed_column USING GIN (cloudevent jsonb_path_ops);
```
